version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    logging:
        driver: none

  hunts-pyro-services:
    image: huntsmanarray/drp-lsst:develop
    container_name: hunts-pyro-services
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
      - ${HUNTSMAN_LOG_DIR}:/opt/lsst/software/stack/huntsman-logs
    environment:
      - HUNTSMAN_ARCHIVE=/home/lsst/huntsman-archive
    command: /opt/lsst/software/stack/huntsman-drp/scripts/pyro/start-pyro-services.sh

  python-tests:
    image: huntsmanarray/drp-lsst:develop
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    depends_on:
      - mongo
      - hunts-pyro-services
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
      - ${HUNTSMAN_LOG_DIR}:/opt/lsst/software/stack/huntsman-logs
    environment:
      - HUNTSMAN_ARCHIVE=/home/lsst/huntsman-archive
    command: /opt/lsst/software/stack/huntsman-drp/scripts/testing/run-docker-tests.sh
