version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    logging:
        driver: none
  python_tests:
    image: huntsmanarray/drp:develop
    depends_on:
    - mongo
    build:
      context: "${HUNTSMAN_DRP}/docker"
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
      - HUNTSMAN_MOUNT=/opt/lsst/software/stack/huntsman
    command: /opt/lsst/software/stack/huntsman-drp/scripts/testing/run_docker_tests.sh
