version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    logging:
        driver: none

  python-tests:
    image: huntsmanarray/drp-lsst:develop
    depends_on:
      - mongo
    build:
      context: "docker"
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
    command: /opt/lsst/software/stack/huntsman-drp/scripts/testing/run-docker-tests.sh
