fits_header:
  mappings:
    expTime: "EXPTIME"
    ccdTemp: "CCD-TEMP"
    expId: "IMAGEID"
    taiObs: "DATE-OBS"
    field: "FIELD"
  required_columns:
    - "expTime"
    - "taiObs"
    - "field"
    - "expId"
    - "ccdTemp"
    - "dateObs"
    - "dataType"
    - "filter"
    - "visit"
    - "ccd"

camera_mappings:
  TESTCAM01: 1
  TESTCAM02: 2
  83F010774: 1

mongodb:
  hostname: "localhost"
  port: 27017
  db_name: "huntsman"
  tables:
    raw_data: "raw_data"

refcat:
  tap_url: http://api.skymapper.nci.org.au/aus/tap/
  tap_table: dr3.master
  ra_key: raj2000
  dec_key: dej2000
  unique_source_key: object_id
  cone_search_radius: 2
  parameter_ranges:
    class_star:
      lower: 0.9
    g_psf:
      upper: 16
