fits_header:
  mappings:
    expTime: "EXPTIME"
    ccdTemp: "CCD-TEMP"
    expId: "IMAGEID"
    taiObs: "DATE-OBS"
    field: "FIELD"
    filter: "FILTER"
  required_columns:
    - "expTime"
    - "taiObs"
    - "field"
    - "expId"
    - "ccdTemp"
    - "dateObs"
    - "dataType"
    - "filter"
    - "visit"
    - "ccd"

camera_mappings:
  "1815420013090900": 1
  "371d420013090900": 2
  "0e2c420013090900": 3
  "0f1d420013090900": 4
  "361d420013090900": 5
  "3528420013090900": 6
  "370d420013090900": 7
  "1919420013090900": 8
  "2d194b0013090900": 9
  "2014420013090900": 10
  "TESTCAM01": 11
  "TESTCAM02": 12
  "83F010774": 13
  "83F011167": 14
  "83F011791": 15
  "83F010801": 16
  "83F011758": 17
  "83F011810": 18

mongodb:
  hostname: "localhost"
  port: 27017
  db_name: "huntsman"
  tables:
    raw_data: "raw_data"

refcat:
  tap_url: http://api.skymapper.nci.org.au/aus/tap/
  tap_table: dr3.master
  ra_key: raj2000
  dec_key: dej2000
  unique_source_key: object_id
  cone_search_radius: 1
  parameter_ranges:
    class_star:
      lower: 0.9
    g_psf:
      upper: 19
