type: huntsman.drp.reduction.lsst.LsstReduction
name: example-reduction

query:
  document_filter:
    dataType: science
    field: DoradoGroup-p0p0
    filter:
      in:
        - g_band
  screen: true
  quality_filter: true
  limit: 1

calexp_kwargs:
  extra_config:
    charImage.background.algorithm: CONSTANT
