type: huntsman.drp.reduction.offsetsky.OffsetSkyReduction
name: example-offsetsky-reduction

# This query is used to select science / target exposures
query:
  document_filter:
    observation_type: science
    object: DoradoGroup-p0p0
    physical_filter:
      in:
        - g_band
  screen: true
  quality_filter: true
  limit: 1

# This query is used to select offset sky exposures
sky_query:
  document_filter:
    observation_type: science
    object: DoradoGroup-p0p0_sky
    physical_filter:
      in:
        - g_band
  screen: true
  quality_filter: true
  limit: 1

# This is the maximum allowed time difference between target and sky exposures
timedelta_minutes: 60

# Define the pipeline to process the offset sky exposures
# This is run before processing the science exposures
offsetsky_pipeline:
  imports:
   - location: ${OBS_HUNTSMAN}/lsst/pipelines/ProcessCcd.yaml
   tasks:
     makeOffsetSkyBackground:
       class: lsst.obs.huntsman.makeOffsetSkyBackground.MakeOffsetSkyBackgroundTask

# Define the pipeline to process the science exposures
pipeline:
  description: "Calibrate raw exposures and make coadds"
  tasks:
  imports:
   - location: ${OBS_HUNTSMAN}/lsst/pipelines/ProcessCcd.yaml
  tasks:
    makeWarp:
      class: lsst.pipe.tasks.makeCoaddTempExp.MakeWarpTask
    assembleCoadd:
      class: lsst.pipe.tasks.assembleCoadd.AssembleCoaddTask
