version: '3'
services:
  lsst_stack:
    image: huntsmanarray/drp:develop
    user: root
    stdin_open: true
    tty: true
    network: host
    volumes:
      - "$OBS_HUNTSMAN:/opt/lsst/software/stack/stack/current/Linux64/obs_huntsman"
      - "$HUNTSMAN_DRP:/opt/lsst/software/stack/stack/current/Linux64/huntsman-drp"
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/stack/current/Linux64/obs_huntsman
      - HUNTSMAN_DRP:/opt/lsst/software/stack/stack/current/Linux64/huntsman-drp
  lsst_firefly:
    image: ipac/firefly:lsst-dev
    ports:
      - "8080:8080"
    environment:
      - "MAX_JVM_SIZE=8G"
