version: "3"

volumes:
  obs_huntsman:
    driver: local
    driver_opts:
      type: none
      device: ${OBS_HUNTSMAN}
      o: bind
  huntsman_drp:
    driver: local
    driver_opts:
      type: none
      device: ${HUNTSMAN_DRP}
      o: bind
  huntsman_mount:
    driver: local
    driver_opts:
      type: none
      device: ${HUNTSMAN_MOUNT}
      o: bind
  huntsman_datadir:
    driver: local
    driver_opts:
      type: none
      device: /data/nifi/huntsman_priv
      o: bind

services:
  lsst_stack:
    image: huntsmanarray/drp-lsst:develop
    logging:
      driver: "none"
    build:
      context: "${HUNTSMAN_DRP}/docker"
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - obs_huntsman:/opt/lsst/software/stack/obs_huntsman
      - huntsman_drp:/opt/lsst/software/stack/huntsman-drp
      - huntsman_mount:${HUNTSMAN_MOUNT}
      - huntsman_datadir:/data/nifi/huntsman_priv
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
      - HUNTSMAN_MOUNT=${HUNTSMAN_MOUNT}
  screening:
    image: huntsmanarray/drp:develop
    build:
      context: "${HUNTSMAN_DRP}/docker/screening"
    network_mode: "host"
    restart: on-failure
    stdin_open: true
    tty: true
    volumes: # screener image built on panoptes-plate-solver
      - obs_huntsman:/home/obs_huntsman
      - huntsman_drp:/home/huntsman-drp
      - huntsman_mount:${HUNTSMAN_MOUNT}
      - huntsman_datadir:/data/nifi/huntsman_priv
    environment:
      - OBS_HUNTSMAN=/home/obs_huntsman
      - HUNTSMAN_DRP=/home/huntsman-drp
      - HUNTSMAN_MOUNT=${HUNTSMAN_MOUNT}
    command: python /home/huntsman-drp/scripts/quality/initial-data-quality-monitor.py

  data-quality-monitor:
    image: huntsmanarray/drp-lsst:develop
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - obs_huntsman:/opt/lsst/software/stack/obs_huntsman
      - huntsman_drp:/opt/lsst/software/stack/huntsman-drp
      - huntsman_mount:${HUNTSMAN_MOUNT}
      - huntsman_datadir:/data/nifi/huntsman_priv
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
      - HUNTSMAN_MOUNT=${HUNTSMAN_MOUNT}
    command: python /opt/lsst/software/stack/huntsman-drp/scripts/quality/calexp-quality-monitor.py
