ARG base_image=lsstsqre/centos:7-stack-lsst_distrib-v20_0_0
FROM ${base_image}

ENV LSST_HOME /opt/lsst/software/stack

USER root
RUN yum install -y wget vim && \
  #Install git-LFS
  export GITLFS=git-lfs-linux-amd64-v2.10.0.tar.gz && \
  cd "${LSST_HOME}/_build" && \
  wget "https://github.com/git-lfs/git-lfs/releases/download/v2.10.0/${GITLFS}" && \
  tar -zxf ${GITLFS} && \
  ./install.sh && \
  rm install.sh && \
  rm -rf ${GITLFS} && \
  #Setup git-LFS for LSST (https://pipelines.lsst.io/v/DM-11077/install/git-lfs.html)
  echo "[credential \"https://lsst-sqre-prod-git-lfs.s3-us-west-2.amazonaws.com\"]" >> ~/.gitconfig && \
  echo -e "\thelper=store" >> ~/.gitconfig && \
  echo "[credential \"https://s3.lsst.codes\"]" >> ~/.gitconfig && \
  echo -e "\thelper=store" >> ~/.gitconfig && \
  touch ~/.git-credentials && \
  echo "https://:@lsst-sqre-prod-git-lfs.s3-us-west-2.amazonaws.com" >> ~/.git-credentials && \
  echo "https://:@s3.lsst.codes" >> ~/.git-credentials && \
  # Install extra python stuff into LSST conda env
  . ${LSST_HOME}/loadLSST.bash && \
  pip install ipython pymongo astroquery

# install astrometry.net dependencies:
RUN yum install -y bzip2
RUN yum install -y bzip2-devel
RUN yum install -y cairo-devel
RUN yum install -y libjpeg-devel
RUN yum install -y libpng-devel
RUN yum install -y libXrender-devel
RUN yum install -y netpbm-devel
RUN yum install -y netpbm-progs
RUN yum install -y netpbm
RUN yum install -y xorg-x11-proto-devel
RUN yum install -y zlib-devel
# NB: yum install was failing to find the wcslib package
RUN wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/w/wcslib-devel-4.25.1-1.el7.1.x86_64.rpm
RUN rpm -Uvh epel-release*rpm
#RUN rpm -ivh wcslib-devel-4.25.1-1.el7.1.x86_64.rpm
RUN yum install wcslib-devel
RUN yum install -y python3 python3-devel
RUN yum install -y swig.x86_64

# install latest cfitsio
RUN CFITS_URL=http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio_latest.tar.gz && \
  curl -L  $CFITS_URL > cfitsio.tar.gz && \
  tar zxvf cfitsio*.tar.gz && \
  cd cfitsio*/ && \
  ./configure --prefix=/usr && \
  make && \
  make install && \
  ln -s /usr/lib/pkgconfig/cfitsio.pc /usr/lib64/pkgconfig/cfitsio.pc && \
  cd .. && \
  rm -rf cfitsio/ && \
  rm -f cfitsio.tar.gz

# python:
RUN python3 -m pip install fitsio astropy

# Astrometry.net installation
COPY ./astrometry /install/astrometry
WORKDIR /
RUN ["/install/astrometry/compile_astrometry.sh"]
ENV PATH="/usr/local/astrometry/bin:${PATH}"
ENV PYTHONPATH="/astrometry.net"

# POCS utils installation
RUN python3 -m pip install panoptes-utils
RUN yum -y install fpack


WORKDIR ${LSST_HOME}
ADD ./../scripts/plate_solve_directory.py .
ADD bash_config.sh .
RUN cat bash_config.sh >> ~/.bashrc
CMD ["/bin/bash"]
