version: '3'
services:
  lsst_stack:
    image: huntsmanarray/drp:develop
    logging:
      driver: "none"
    build:
      context: "${HUNTSMAN_DRP}/docker"
    network_mode: "host"
    stdin_open: true
    tty: true
    ports:    # needed to run Jupyter nb from container
      - "9888:9888"
      - "9889:9889"
      - "9890:9890"
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
      - ${HUNTSMAN_MOUNT}:${HUNTSMAN_MOUNT}
      - /data/nifi/huntsman_priv:/data/nifi/huntsman_priv
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
      - HUNTSMAN_MOUNT=${HUNTSMAN_MOUNT}
  screening:
      image: huntsmanarray/screener:develop
      logging:
        driver: "none"
      build:
        context: "${HUNTSMAN_DRP}/docker/screening"
      network_mode: "host"
      stdin_open: true
      tty: true
      volumes:    # screener image built on panoptes-plate-solver
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/home/screener/huntsman-drp
      - ${HUNTSMAN_MOUNT}:${HUNTSMAN_MOUNT}
      - /data/nifi/huntsman_priv:/data/nifi/huntsman_priv
      environment:
        - OBS_HUNTSMAN=/home/obs_huntsman
        - HUNTSMAN_DRP=/home/huntsman-drp
        - HUNTSMAN_MOUNT=${HUNTSMAN_MOUNT}
