ARG base_image=lsstsqre/centos:7-stack-lsst_distrib-v20_0_0
FROM ${base_image}

ENV LSST_HOME /opt/lsst/software/stack

USER root
RUN yum install -y wget vim && \
  #Install git-LFS
  export GITLFS=git-lfs-linux-amd64-v2.10.0.tar.gz && \
  cd "${LSST_HOME}/_build" && \
  wget "https://github.com/git-lfs/git-lfs/releases/download/v2.10.0/${GITLFS}" && \
  tar -zxf ${GITLFS} && \
  ./install.sh && \
  rm install.sh && \
  rm -rf ${GITLFS} && \
  #Setup git-LFS for LSST (https://pipelines.lsst.io/v/DM-11077/install/git-lfs.html)
  echo "[credential \"https://lsst-sqre-prod-git-lfs.s3-us-west-2.amazonaws.com\"]" >> ~/.gitconfig && \
  echo -e "\thelper=store" >> ~/.gitconfig && \
  echo "[credential \"https://s3.lsst.codes\"]" >> ~/.gitconfig && \
  echo -e "\thelper=store" >> ~/.gitconfig && \
  touch ~/.git-credentials && \
  echo "https://:@lsst-sqre-prod-git-lfs.s3-us-west-2.amazonaws.com" >> ~/.git-credentials && \
  echo "https://:@s3.lsst.codes" >> ~/.git-credentials && \
  # Install extra python stuff into LSST conda env
  . ${LSST_HOME}/loadLSST.bash && \
  pip install ipython pymongo astroquery panoptes-utils && \
  # Astrometry.net dependencies
  yum install -y epel-release && \
  yum install -y bzip2 && \
  yum install -y bzip2-devel && \
  yum install -y cairo-devel && \
  yum install -y libjpeg-devel && \
  yum install -y libpng-devel && \
  yum install -y libXrender-devel && \
  yum install -y netpbm-devel && \
  yum install -y netpbm-progs && \
  yum install -y netpbm && \
  yum install -y xorg-x11-proto-devel && \
  yum install -y zlib-devel && \
  yum install -y wcslib-devel.x86_64 && \
  yum install -y python3 python3-devel && \
  yum install -y swig.x86_64 && \
  yum install -y fpack && \
  # Compile/install astrometry
  # link cfitsio to place where astrometry,net make will find it
  echo "export LD_LIBRARY_PATH=/usr/lib64:${LD_LIBRARY_PATH}" >> /opt/lsst/software/stack/conda/miniconda3-py37_4.8.2/envs/lsst-scipipe-1a1d771/etc/conda/activate.d && \
  ln -s /opt/lsst/software/stack/conda/miniconda3-py37_4.8.2/pkgs/cfitsio-3.470-h3eac812_5/lib/pkgconfig/cfitsio.pc /usr/lib64/pkgconfig/cfitsio.pc && \
  # set environment variables:
  export PATH=${PATH}:/usr/local/astrometry/bin && \
  # clone the repo:
  git clone https://github.com/dstndstn/astrometry.net.git ${LSST_HOME}/astrometry.net && \
  cd ${LSST_HOME}/astrometry.net && \
  cd util && \
  ORIGINAL_LINE_START='NETPBM_INC.*' && \
  REPLACE_WITH='NETPBM_INC ?= -I\/usr\/include\/netpbm\/' && \
  sed -i "s/$ORIGINAL_LINE_START/$REPLACE_WITH/g" makefile.netpbm && \
  ORIGINAL_LINE_START='NETPBM_LIB.*' && \
  REPLACE_WITH='NETPBM_LIB ?= -L\/usr\/lib64 -lnetpbm' && \
  sed -i "s/$ORIGINAL_LINE_START/$REPLACE_WITH/g" makefile.netpbm && \
  cd .. && \
  # compile/install:
  make config > config_results && \
  make && \
  make extra && \
  make py && \
  make install

# astrometry env vars
ENV PATH="/usr/local/astrometry/bin:${PATH}"
ENV PYTHONPATH="${LSST_HOME}/astrometry.net"

WORKDIR ${LSST_HOME}
ADD bash_config.sh .
RUN cat bash_config.sh >> ~/.bashrc
CMD ["/bin/bash"]
