directories:
  archive: ${HUNTSMAN_ARCHIVE}
  calib: ${HUNTSMAN_ARCHIVE}/calib
  reductions: ${HUNTSMAN_ARCHIVE}/reductions
  plots: ${HUNTSMAN_ARCHIVE}/plots

# Config items for connecting to the mongodb client
mongodb:
  hostname: "localhost"
  port: 27017
  db_name: "huntsman"

# Configurations for Pyro services
pyro:
  host: localhost  # Hostname of the Pyro server
  port: 6563  # Port of the pyro name server
  refcat:  # kwargs that are parsed to init function of refcat client
    name: "refcat"

# Config for collections
collections:
  # Exposure collections contain metadata for raw exposures
  ExposureCollection:
    name: "huntsman_exposures"  # The name of the mongodb collection
    required_fields:  # Required fields must be present in an inserted document
      - filename
    index_fields:
      - filename
  # Calib collections contain metadata for master calibs
  CalibCollection:
    name: "huntsman_calibs"
    required_fields:
      - "filename"
      - "raw_filenames"
      - "date"
      - "datasetType"
      - "instrument"
      - "detector"
    required_fields_by_type:
      flat:
        - "physical_filter"
    index_fields:
      - filename
  # ReferenceCalibCollection stores examples of good raw calibs for quality control
  ReferenceCalibCollection:
    name: "huntsman_reference_calibs"
    required_fields:
      - "filename"
      - "date"
      - "observation_type"
      - "instrument"
      - "detector"
    required_fields_by_type:
      flat:
        - "physical_filter"
    index_fields:
      - filename

# Config items for the QualityMonitor service
QualityMonitor:
  pipeline_config:  # LSST task overrides
    "calibrate:doDeblend": false  # Turn off deblending to save compute resources

# Config items for calibs
calibs:
  types:  # In order of creation
    - bias
    - defects
    - dark
    - flat
  # These columns are for matching raw calibs with raw science frames
  # They are defined in lsst/cp_pipe and also here for convenience
  # If these are changed then all of the archived calibs will need to be renamed
  required_fields:
    flat:
      - instrument
      - detector
      - physical_filter
    bias:
      - instrument
      - detector
    dark:
      - instrument
      - detector
    defects:
      - instrument
      - detector

refcat:
  tap_url: https://api.skymapper.nci.org.au/aus/tap/
  tap_table: dr3.master
  ra_key: raj2000
  dec_key: dej2000
  unique_source_key: object_id
  cone_search_radius: 1
  parameter_ranges:
    class_star:
      lower: 0.9
    g_psf:
      upper: 15
    flags:
      equal: 0

quality:
  raw:
    science:
      metrics:
        has_wcs: true
  flat:
    metrics:
      flip_asymm_h:
        "$lt": 100
      flip_asymm_v:
        "$lt": 60
      well_fullfrac:
        greater_than: 0.13
        "$lt": 0.19

plotter:
  # List of kwargs for individual plotters
  # kwargs are parsed directly to init function of each plotter
  - directory_prefix: "default"
    plot_configs:
      plot_by_camera_filter:
        - x_key: "AIRMASS"
          y_key: "metrics.calexp.zp_mag"
      hist_by_camera_filter:
        - "metrics.calexp.psf_fwhm_arcsec"
        - "metrics.calexp.zp_mag"

# Camera info, mainly used by obs_huntsman
# TODO: Move to obs_huntsman?
cameras:
  plate_scale: 527.54167  # arcsec/mm
  default_preset: "zwo"
  presets:
    zwo:
      width: 5496
      height: 3672
      saturation: 4094
      gain: 1.145
      read_noise: 2.4
      pixel_size: 0.0024  # mm (?)
      overscan: 0
  devices:
    - camera_name: "1815420013090900"
    - camera_name: "371d420013090900"
    - camera_name: "0e2c420013090900"
    - camera_name: "0f1d420013090900"
    - camera_name: "361d420013090900"
    - camera_name: "3528420013090900"
    - camera_name: "370d420013090900"
    - camera_name: "1919420013090900"
    - camera_name: "2d194b0013090900"
    - camera_name: "2014420013090900"
    - camera_name: "11360f0405080900"
    - camera_name: "TESTCAM01"
      width: 100
      height: 100
    - camera_name: "TESTCAM02"
      width: 100
      height: 100
    - camera_name: "TESTCAM03"
      width: 800
      height: 800
