directories:
  archive: ${HUNTSMAN_ARCHIVE}

fits_header:
  date_key: "DATE-OBS"
  mappings:
    expTime: "EXPTIME"
    ccdTemp: "CCD-TEMP"
    expId: "IMAGEID"
    taiObs: "DATE-OBS"
    field: "FIELD"
    filter: "FILTER"
  required_columns:
    - "expTime"
    - "taiObs"
    - "field"
    - "expId"
    - "ccdTemp"
    - "dateObs"
    - "dataType"
    - "filter"
    - "visit"
    - "ccd"

cameras:
  plate_scale: 527.54167  # arcsec/mm
  default_preset: "zwo"
  presets:
    zwo:
      width: 5496
      height: 3672
      saturation: 4095
      gain: 1.145
      read_noise: 2.4
      pixel_size: 0.0024  # mm (?)
      overscan: 0
  devices:
    - camera_name: "1815420013090900"
    - camera_name: "371d420013090900"
    - camera_name: "0e2c420013090900"
    - camera_name: "0f1d420013090900"
    - camera_name: "361d420013090900"
    - camera_name: "3528420013090900"
    - camera_name: "370d420013090900"
    - camera_name: "1919420013090900"
    - camera_name: "2d194b0013090900"
    - camera_name: "2014420013090900"
    - camera_name: "TESTCAM01"
      width: 100
      height: 100
    - camera_name: "TESTCAM02"
      width: 100
      height: 100
    - camera_name: "TESTCAM03"
      width: 800
      height: 800

mongodb:
  hostname: "localhost"
  port: 27017
  db_name: "huntsman"
  collections:
    RawExposureCollection:
      name: "raw_exposures"
      unique_keys:
        - "filename"
    MasterCalibCollection:
      name: "master_calibs"
      unique_keys:
        - "filename"  # Let obs_huntsman handle unique calib file naming

calibs:
  types:  # Order might be important...
    - bias
    - dark
    - flat
  validity: 30
  matching_columns:  # These columns are for matching raw calibs with raw science frames
    flat:
      - filter
      - ccd
    bias:
      - ccd
    dark:
      - ccd

refcat:
  tap_url: http://api.skymapper.nci.org.au/aus/tap/
  tap_table: dr3.master
  ra_key: raj2000
  dec_key: dej2000
  unique_source_key: object_id
  cone_search_radius: 1
  parameter_ranges:
    class_star:
      lower: 0.9
    g_psf:
      upper: 15
    flags:
      equal: 0

quality:
  raw:
    science:
      metrics:
        has_wcs: true
    flat:
      metrics:
        flip_asymm_h:
          less_than: 100
        flip_asymm_v:
          less_than: 60
        well_fullfrac:
          greater_than: 0.13
          less_than: 0.19

pyro:
  host: localhost
  port: 6563
  refcat:
    name: "refcat"
