directories:
  testdata: ${HUNTSMAN_DRP}/tests/data

exposure_sequence:
  start_date: "2020-02-04"
  n_cameras: 2
  n_days: 2   # Simulate this number of nights
  n_flat: 2   # Per (filter, camera) pair per night
  n_bias: 2   # Per camera per night
  n_dark: 2   # Per (exposure time, camera) pair per night
  n_science: 1  # Per (camera, field, filter) combination per night
  exptime_flat: 30
  exptime_science: 60
  filters:
    - "g_band"
    - "r_band"
  size_x: 100
  size_y: 100
  dtype: uint16
  saturate: 4096  # ADU
  bias: 32  # ADU
  pixel_size: 1.2  # Arcseconds per pixel

mongodb:
  collections:
    ExposureCollection:
      name: "test_real_data"

pyro:
  refcat:
    name: test_refcat

CalibService:
  validity: 9999

plotter:
  - directory_prefix: "test1"
    plot_configs:
      plot_by_camera:
        - x_key: "exposure_time"
          y_key: "metrics.clipped_mean"
      plot_by_camera_filter:
        - x_key: "exposure_time"
          y_key: "metrics.clipped_mean"
          linewidth: 2
      hist_by_camera_filter:
        - key: "metrics.clipped_mean"
          color: "red"
  - directory_prefix: "test2"
    find_kwargs:
      document_filter:
        physical_filter: "g_band"
    plot_configs:
      plot_by_camera:
        - x_key: "exposure_time"
          y_key: "metrics.clipped_mean"

raw_metrics_ignore:
  - get_wcs
