version: '3'
services:
  lsst_stack:
    image: huntsmanarray/drp:develop
    logging:
      driver: "none"
    build:
      context: "${HUNTSMAN_DRP}/docker"
    network_mode: "host"
    stdin_open: true
    tty: true
    ports:
      - "9888:9888"
      - "9889:9889"
      - "9890:9890"
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
      - ${BUTLER_DIRECTORY}:/opt/lsst/software/stack/mount
      - /data/nifi/huntsman_priv:/data/nifi/huntsman_priv
      - ${ASTROMETRY_INDEX_DATA}:/usr/local/astrometry/data
      - ${ASTROMETRY_INPUT_DATA}:/mnt
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
