version: '3'
services:
  lsst_stack:
    image: huntsmanarray/drp:develop
    build:
      context: "${HUNTSMAN_DRP}/docker"
    user: root
    network_mode: "host"
    stdin_open: true
    tty: true
    ports:
      - "9888:9888"
      - "9889:9889"
      - "9890:9890"
    volumes:
      - ${OBS_HUNTSMAN}:/opt/lsst/software/stack/obs_huntsman
      - ${HUNTSMAN_DRP}:/opt/lsst/software/stack/huntsman-drp
      - ${OBS_HUNTSMAN_TESTDATA}:/opt/lsst/software/stack/testdata
      - ${DATA}:/opt/lsst/software/stack/DATA
    environment:
      - OBS_HUNTSMAN=/opt/lsst/software/stack/obs_huntsman
      - HUNTSMAN_DRP=/opt/lsst/software/stack/huntsman-drp
      - FIREFLY_URL=http://${LOCAL_MACHINE_IP}:8080/firefly
  lsst_firefly:
    image: ipac/firefly:lsst-dev
    ports:
      - "8080:8080"
    environment:
      - "MAX_JVM_SIZE=8G"
