name: Docker CI
on:
  push:
    branches:
    - develop
jobs:
  env:
    HTML: ${{ github.workspace }}/html
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Build and push huntsmanarray/drp-lsst:develop image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: huntsmanarray/drp-lsst:develop
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
    -
      name: Build and push huntsmanarray/drp:develop image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: huntsmanarray/drp:develop
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/ingestor/Dockerfile
    -
      name: Build docs
      image: huntsmanarray/drp-lsst:develop
      env:
        DRP: /opt/lsst/software/stack/huntsman-drp
      run: |
        docker run --rm -v ${HTML}:${DRP}/docs/build/html huntsmanarray/drp-lsst:develop ${DRP}/scripts/build-docs.sh
    -
      name: Publish docs
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: ${HTML}
        target-folder: html
